
markdown: kramdown
theme: jekyll-theme-tactile
remote_theme: pages-themes/tactile@v0.2.0
plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme

# Main site settings
locale          : "en-GB"
title           : "Chris Pedro"
title_seperator : "-"
description     : "Just a guy from Bermuda"
name            : &name "Chris Pedro"
url             : https://chris.thepedros.com
repository      : "cpedro/cpedro.github.io"
google_analytics: "UA-131160048-1"

author:
  name    : "Chris Pedro"
  location: "Bermuda"

# Date format: See http://strftime.net/
date_format: "%Y-%m-%d"

collections:
  tech:
    output: true
    permalink: /:collection/:path/

# Social links, will appear in order listed.
social:
  links:
    - title: "GitHub"
      url: "https://github.com/cpedro"
      icon: "socicon-github"
    - title: "Linkedin"
      url: "https://www.linkedin.com/in/chris-pedro-3317a023/"
      icon: "socicon-linkedin"
    - title: "Mastodon"
      url: "https://fosstodon.org/@aner"
      icon: "socicon-mastodon"
    - title: "Twitter"
      url: "https://twitter.com/Aner_san"
      icon: "socicon-twitter"
    - title: "Email"
      url: "&#109;&#097;&#105;&#108;&#116;&#111;:&#097;&#110;&#101;&#114;&#064;&#100;&#117;&#099;&#107;&#046;&#099;&#111;&#109;"
      icon: "socicon-mail"
