
markdown: kramdown
theme: jekyll-theme-tactile
plugins:
  - jekyll-seo-tag

# Main site settings
locale          : "en-GB"
title           : "Chris Pedro"
title_seperator : "-"
description     : "Just a guy from Bermuda"
name            : &name "Chris Pedro"
url             : https://chris.thepedros.com
repository      : "cpedro/cpedro.github.io"
google_analytics: "UA-131160048-1"

author:
  name    : "Chris Pedro"
  location: "Bermuda"

# Date format: See http://strftime.net/
date_format: "%Y-%m-%d"

collections:
  tech:
    output: true
    permalink: /:collection/:path/

# Social links, will appear in order listed.
social:
  links:
    - title: "GitHub"
      url: "https://github.com/cpedro"
      icon: "socicon-github"
    - title: "Twitter"
      url: "https://twitter.com/Aner_san"
      icon: "socicon-twitter"
    - title: "Linkedin"
      url: "https://www.linkedin.com/in/chris-pedro-3317a023/"
      icon: "socicon-linkedin"
    - title: "Email"
      url: "&#109;&#97;&#105;&#108;&#116;&#111;&#58;&#99;&#104;&#114;&#105;&#115;&#64;&#116;&#104;&#101;&#112;&#101;&#100;&#114;&#111;&#115;&#46;&#99;&#111;&#109;"
      icon: "socicon-mail"
